/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import daos.ArrondissementDAO;
import daos.Globale;
import entities.Arrondissement;
import java.awt.Component;
import java.awt.Rectangle;
import java.sql.*;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rayanakel
 */
public class JIFArrondissements extends javax.swing.JInternalFrame {

    private Connection icn;
    private DefaultTableModel idtm;

    /**
     * Creates new form JIFArrondissements
     */
    public JIFArrondissements() {
        initComponents();

        setTitle("CRUD Arrondissements");
        setVisible(true);

        jTextFieldId.setText("ID");
        jTextFieldCode.setText("");
        jTextFieldNom.setText("");

        try {
            icn = Globale.getCnx();
            System.out.println(icn);
            /*
             Recuperation du Model de la jTable
             */
            idtm = (DefaultTableModel) jTableArrondissements.getModel();

        } catch (Exception ex) {
            jLabelMessage.setText(ex.getMessage());
        }

        remplirJTable();

//        try {
//            // --- Connexion
//            String lsDSN = "jdbc:mysql://127.0.0.1:8889/cinescope2014";
//            icn = DriverManager.getConnection(lsDSN, "root", "root");
//
//            //Affichage des donnees de la table departement
//            PreparedStatement lpst = icn.prepareStatement("SELECT * FROM arrondissement");
//            ResultSet lrs = lpst.executeQuery();
//
//            Object[] tLigne;
//
//            DefaultTableModel ldtm = (DefaultTableModel) jTableArrondissements.getModel();
//
//            while (lrs.next()) {
//                tLigne = new Object[3];
//
//                tLigne[0] = lrs.getString(1);
//                tLigne[1] = lrs.getString(2);
//                tLigne[2] = lrs.getString(3);
//
//                ldtm.addRow(tLigne);
//            }
//
//            lrs.close();
//            lpst.close();
//
//            jLabelMessage.setText("Chargement réussi !!");
//
//        } catch (SQLException ex) {
//            jLabelMessage.setText(ex.getMessage());
//        }
    }

    private void remplirJTable() {

        for (int i = idtm.getRowCount() - 1; i >= 0; i--) {
            idtm.removeRow(i);
        }

        try {
            Object[] tLigne;
            ArrondissementDAO dao = new ArrondissementDAO(icn);
            List<Arrondissement> liste = dao.selectAll();
            for (int i = 0; i < liste.size(); i++) {
                Arrondissement arrondissement = liste.get(i);
                tLigne = new Object[3];
                tLigne[0] = arrondissement.getIdArrondissement();
                tLigne[1] = arrondissement.getCodeArrondissement();
                tLigne[2] = arrondissement.getNomArrondissement();
                idtm.addRow(tLigne);
            }

            jLabelMessage.setText("Chargement réussi !!");

        } catch (Exception ex) {
            jLabelMessage.setText(ex.getMessage());
        }

    }

    private void cls() {

        try {
            Component[] tComposants = getContentPane().getComponents();
            for (int i = 0; i < tComposants.length; i++) {
                Object objet = tComposants[i];
                if (objet.getClass().toString().equals("class javax.swing.JTextField")) {
                    JTextField composant = (JTextField) objet;
                    composant.setText("");
                }
            }
        } catch (Exception e) {
            jLabelMessage.setText(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArrondissements = new javax.swing.JTable();
        jLabelId = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelMessage = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableArrondissements.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableArrondissements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Nom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArrondissements.setGridColor(new java.awt.Color(0, 0, 0));
        jTableArrondissements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArrondissementsMouseClicked(evt);
            }
        });
        jTableArrondissements.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableArrondissementsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArrondissements);

        jLabelId.setText("ID");

        jLabelCode.setText("Code");

        jLabelNom.setText("Nom");

        jTextFieldId.setBackground(new java.awt.Color(238, 238, 238));
        jTextFieldId.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldId.setText("ID");
        jTextFieldId.setToolTipText("");
        jTextFieldId.setBorder(null);

        jLabelMessage.setText("Message");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjouter)
                        .addGap(143, 143, 143)
                        .addComponent(jButtonModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSupprimer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMessage)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNom)
                                            .addComponent(jLabelCode))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCode)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:

        int liAffecte;

        if (jTextFieldCode.getText().isEmpty() || jTextFieldNom.getText().isEmpty()) {

            jLabelMessage.setText("Veuillez renseigner tout les champs!!");
        } else {
            try {

                ArrondissementDAO dao = new ArrondissementDAO(icn);

                // Insert
                Arrondissement di = new Arrondissement(jTextFieldCode.getText(), jTextFieldNom.getText());
                liAffecte = dao.insert(di);
                if (liAffecte == 1) {
                    icn.commit();
                    remplirJTable();
                    int liMax = jTableArrondissements.getRowCount() - 1;
                    jTableArrondissements.getSelectionModel().setSelectionInterval(liMax, liMax);
                    jTableArrondissements.scrollRectToVisible(new Rectangle(jTableArrondissements.getCellRect(liMax, 0, true)));
                }
                jLabelMessage.setText("Ajout réussi !");

                cls();
//
//                // INSERTION
//                String lsSQL = "INSERT INTO arrondissement (CODE_arrondissement, NOM_arrondissement) VALUES(?,?)";
//
//                PreparedStatement lpst = icn.prepareStatement(lsSQL);
//
//                //Recuperation des donnes dans les champs
//                lpst.setString(1, jTextFieldCode.getText());
//                lpst.setString(2, jTextFieldNom.getText());
//
//                //Execution
//                lpst.executeUpdate();
//
//                Object[] tLigne;
//
//                DefaultTableModel ldtm = (DefaultTableModel) jTableArrondissements.getModel();
//
//                tLigne = new Object[3];
//
//                tLigne[1] = jTextFieldCode.getText();
//                tLigne[2] = jTextFieldNom.getText();
//
//                ldtm.addRow(tLigne);
//
//                lpst.close();
//
//                jLabelMessage.setText("Ajout réussi !");

            } catch (SQLException ex) {
                jLabelMessage.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here

        if (jTextFieldCode.getText().isEmpty() || jTextFieldNom.getText().isEmpty()) {

            jLabelMessage.setText("Veuillez sélectionner une ligne.");
        } else {
            int liAffecte;

            try {
                ArrondissementDAO dao = new ArrondissementDAO(icn);

                // Update
                Arrondissement di = new Arrondissement(Integer.valueOf(jTextFieldId.getText()), jTextFieldCode.getText(), jTextFieldNom.getText());
                liAffecte = dao.update(di);
                if (liAffecte == 1) {
                    icn.commit();
                    remplirJTable();
                    cls();
                }
                jLabelMessage.setText("Arrondissement modifié !");

            } catch (SQLException e) {
                jLabelMessage.setText(e.getMessage());
            }
        }

//        int liSelectedRow = this.jTableArrondissements.getSelectedRow();
//
//        if (jTextFieldCode.getText().isEmpty() || jTextFieldNom.getText().isEmpty()) {
//
//            jLabelMessage.setText("Veuillez choisir un arrondissement.");
//        } else {
//            try {
//                // MODIFICATION
//                String lstSQL = "UPDATE arrondissement SET code_arrondissement = ?, nom_arrondissement = ? WHERE id_arrondissement = ?";
//
//                PreparedStatement lpst = icn.prepareStatement(lstSQL);
//
//                //Recuperation des valeurs dans les champs et update de la table
//                lpst.setString(1, jTextFieldCode.getText());
//                lpst.setString(2, jTextFieldNom.getText());
//                lpst.setString(3, jTextFieldId.getText());
//
//                lpst.executeUpdate();
//
//                lpst.close();
//
//                jTableArrondissements.setValueAt(jTextFieldId.getText(), liSelectedRow, 0);
//                jTableArrondissements.setValueAt(jTextFieldCode.getText(), liSelectedRow, 1);
//                jTableArrondissements.setValueAt(jTextFieldNom.getText(), liSelectedRow, 2);
//
//                jLabelMessage.setText("Arrondissement modifié !!!");
//
//            } catch (SQLException ex) {
//                jLabelMessage.setText(ex.getMessage());
//            }
//        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:

        if (jTextFieldCode.getText().isEmpty() || jTextFieldNom.getText().isEmpty()) {

            jLabelMessage.setText("Veuillez sélectionner une ligne.");
        } else {
            int liAffecte;
            try {
                ArrondissementDAO dao = new ArrondissementDAO(icn);

                // Delete
                Arrondissement dd = new Arrondissement(Integer.valueOf(jTextFieldId.getText()), jTextFieldCode.getText(), jTextFieldNom.getText());
                liAffecte = dao.delete(dd);
                icn.commit();
                if (liAffecte == 1) {
                    icn.commit();
                    remplirJTable();
                    cls();
                }
                jLabelMessage.setText("Arrondissement supprimé !");

            } catch (SQLException e) {
                jLabelMessage.setText(e.getMessage());
            }
        }

//        int liSelectedRow = this.jTableArrondissements.getSelectedRow();
//
//        if (jTextFieldCode.getText().isEmpty() || jTextFieldNom.getText().isEmpty()) {
//
//            jLabelMessage.setText("Veuillez choisir un arrondissement.");
//        } else {
//            try {
//                String lstSQL = "DELETE FROM arrondissement WHERE id_arrondissement = ?";
//
//                PreparedStatement lpst = icn.prepareStatement(lstSQL);
//
//                lpst.setString(1, jTableArrondissements.getValueAt(liSelectedRow, 0).toString());
//
//                lpst.executeUpdate();
//
//                lpst.close();
//
//                DefaultTableModel ldtm = (DefaultTableModel) jTableArrondissements.getModel();
//
//                int tLigne = this.jTableArrondissements.getSelectedRow();
//
//                ldtm.removeRow(tLigne);
//
//                jLabelMessage.setText("Arrondissement supprimé !!!");
//
//            } catch (SQLException ex) {
//                jLabelMessage.setText(ex.getMessage());
//            }
//        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
//        try {
//            icn.close();
//        } catch (SQLException e) {
//            System.err.println(e.getMessage());
//        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTableArrondissementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArrondissementsMouseClicked
        // TODO add your handling code here:
        int liSelectedRow = this.jTableArrondissements.getSelectedRow();

        jTextFieldId.setText(jTableArrondissements.getValueAt(liSelectedRow, 0).toString());
        jTextFieldCode.setText(jTableArrondissements.getValueAt(liSelectedRow, 1).toString());
        jTextFieldNom.setText(jTableArrondissements.getValueAt(liSelectedRow, 2).toString());
    }//GEN-LAST:event_jTableArrondissementsMouseClicked

    private void jTableArrondissementsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableArrondissementsKeyReleased
        // TODO add your handling code here:
        jTableArrondissementsMouseClicked(null);
    }//GEN-LAST:event_jTableArrondissementsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArrondissements;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
