/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author rayanakel
 */
public class JIFModificationPays extends javax.swing.JInternalFrame {

    private Connection icn;
    private DefaultComboBoxModel idcbm;

    /**
     * Creates new form JIFModificationPays
     */
    public JIFModificationPays() {
        initComponents();

        jTextFieldIdPays.setText("");
        jTextFieldNomPays.setText("");
        jTextFieldMasculin.setText("");
        jTextFieldFeminin.setText("");
        jTextFieldNeutre.setText("");

        setVisible(true);
        setTitle("Modification Pays");

        //Connection a la base et affichage des pays dans la combo
        try {
            // --- Connexion
            Class.forName("org.gjt.mm.mysql.Driver");
            String lsDSN = "jdbc:mysql://127.0.0.1:8889/cinescope2014";
            icn = DriverManager.getConnection(lsDSN, "root", "root");

            Statement lstSQL = icn.createStatement();
            ResultSet lrs = lstSQL.executeQuery("SELECT nom_pays FROM pays ORDER BY 1");

            idcbm = new DefaultComboBoxModel();
            while (lrs.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                idcbm.addElement(lrs.getString(1));
            }
            jComboBoxPays.setModel(idcbm);

            lrs.close();
            lstSQL.close();

            jLabelMessage.setText("Veuillez choisir un pays à modifier.");

        } catch (ClassNotFoundException | SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPaysModifier = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jComboBoxPays = new javax.swing.JComboBox<>();
        jLabelIdPays = new javax.swing.JLabel();
        jTextFieldIdPays = new javax.swing.JTextField();
        jLabelNomPays = new javax.swing.JLabel();
        jLabelMasculin = new javax.swing.JLabel();
        jLabelFeminin = new javax.swing.JLabel();
        jButtonValiderModification = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabelNeutre = new javax.swing.JLabel();
        jTextFieldNomPays = new javax.swing.JTextField();
        jTextFieldMasculin = new javax.swing.JTextField();
        jTextFieldFeminin = new javax.swing.JTextField();
        jTextFieldNeutre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modification d'un pays");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelPaysModifier.setText("Pays à modifier");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jComboBoxPays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPays.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPaysItemStateChanged(evt);
            }
        });
        jComboBoxPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaysActionPerformed(evt);
            }
        });

        jLabelIdPays.setText("ID pays");

        jTextFieldIdPays.setBackground(new java.awt.Color(238, 238, 238));
        jTextFieldIdPays.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldIdPays.setText("ID");
        jTextFieldIdPays.setBorder(null);

        jLabelNomPays.setText("Nom du pays");

        jLabelMasculin.setText("Masculin");

        jLabelFeminin.setText("Féminin");

        jButtonValiderModification.setText("Valider la modification");
        jButtonValiderModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderModificationActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        jLabelNeutre.setText("Neutre");

        jTextFieldNomPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomPaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonValiderModification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPaysModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonValider)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMessage)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomPays)
                                    .addComponent(jLabelIdPays)
                                    .addComponent(jLabelMasculin)
                                    .addComponent(jLabelFeminin)
                                    .addComponent(jLabelNeutre))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomPays)
                                    .addComponent(jTextFieldMasculin)
                                    .addComponent(jTextFieldFeminin)
                                    .addComponent(jTextFieldNeutre)
                                    .addComponent(jComboBoxPays, 0, 152, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 209, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaysModifier))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdPays)
                    .addComponent(jTextFieldIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomPays)
                    .addComponent(jTextFieldNomPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMasculin)
                    .addComponent(jTextFieldMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFeminin)
                    .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNeutre)
                    .addComponent(jTextFieldNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonValiderModification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabelMessage))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderModificationActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNomPays.getText().isEmpty() || jTextFieldMasculin.getText().isEmpty() || jTextFieldFeminin.getText().isEmpty() || jTextFieldNeutre.getText().isEmpty()) {

            jLabelMessage.setText("Veuillez renseigner tout les champs!!");
        } else {
            try {
                // MODIFICATION
                String lstSQL = "UPDATE pays SET nom_pays = ?, masculin = ?, feminin = ?, neutre = ? WHERE id_pays = ?";

                PreparedStatement lpst = icn.prepareStatement(lstSQL);

                //Recuperation des valeurs dans les champs et update de la table
                lpst.setString(1, jTextFieldNomPays.getText());
                lpst.setString(2, jTextFieldMasculin.getText());
                lpst.setString(3, jTextFieldFeminin.getText());
                lpst.setString(4, jTextFieldNeutre.getText());
                lpst.setString(5, jTextFieldIdPays.getText());

                lpst.executeUpdate();

                lpst.close();

                jLabelMessage.setText("Pays modifié !!!");

            } catch (SQLException ex) {
                jLabelMessage.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonValiderModificationActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        
        //Affichage des donnees dans les champs
        try {
            String lstSQL = "SELECT * FROM pays WHERE NOM_pays = ?";

            PreparedStatement lpst = icn.prepareStatement(lstSQL);

            lpst.setString(1, jComboBoxPays.getSelectedItem().toString());
            ResultSet lrs = lpst.executeQuery();

            if (lrs.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                jTextFieldIdPays.setText(lrs.getString(1));
                jTextFieldNomPays.setText(lrs.getString(2));
                jTextFieldMasculin.setText(lrs.getString(3));
                jTextFieldFeminin.setText(lrs.getString(4));
                jTextFieldNeutre.setText(lrs.getString(5));
            }

            lrs.close();
            lpst.close();

            jLabelMessage.setText("Veuillez choisir un pays à modifier.");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        try {
            icn.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jComboBoxPaysItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPaysItemStateChanged
        // TODO add your handling code here:
        
        //Méthode pour afficher les champs sans cliquer sur "valider"
        try {
            String lstSQL = "SELECT * FROM pays WHERE NOM_pays = ?";

            PreparedStatement lpst = icn.prepareStatement(lstSQL);

            lpst.setString(1, jComboBoxPays.getSelectedItem().toString());
            ResultSet lrs = lpst.executeQuery();

            if (lrs.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                jTextFieldIdPays.setText(lrs.getString(1));
                jTextFieldNomPays.setText(lrs.getString(2));
                jTextFieldMasculin.setText(lrs.getString(3));
                jTextFieldFeminin.setText(lrs.getString(4));
                jTextFieldNeutre.setText(lrs.getString(5));
            }

            lrs.close();
            lpst.close();

            jLabelMessage.setText("Veuillez choisir un pays à modifier.");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jComboBoxPaysItemStateChanged

    private void jComboBoxPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaysActionPerformed

    private void jTextFieldNomPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomPaysActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JButton jButtonValiderModification;
    private javax.swing.JComboBox<String> jComboBoxPays;
    private javax.swing.JLabel jLabelFeminin;
    private javax.swing.JLabel jLabelIdPays;
    private javax.swing.JLabel jLabelMasculin;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNeutre;
    private javax.swing.JLabel jLabelNomPays;
    private javax.swing.JLabel jLabelPaysModifier;
    private javax.swing.JTextField jTextFieldFeminin;
    private javax.swing.JTextField jTextFieldIdPays;
    private javax.swing.JTextField jTextFieldMasculin;
    private javax.swing.JTextField jTextFieldNeutre;
    private javax.swing.JTextField jTextFieldNomPays;
    // End of variables declaration//GEN-END:variables
}
