/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author rayanakel
 */
public class JIFSuppressionPays extends javax.swing.JInternalFrame {

    //Variables globales
    private Connection icn;
    private DefaultComboBoxModel idcbm;
    //Declaration de la map Pays
    private Map<String, String> mapPays;

    /**
     * Creates new form JIFrameSuppressionPays
     */
    public JIFSuppressionPays() {
        initComponents();

        setTitle("Suppression Pays");
        setVisible(true);
        
        

        //Connection a la base et affichage des pays dans la combo
        try {
            // --- Connexion
            Class.forName("org.gjt.mm.mysql.Driver");
            String lsDSN = "jdbc:mysql://127.0.0.1:8889/cinescope2014";
            icn = DriverManager.getConnection(lsDSN, "root", "root");

            Statement lstSQL = icn.createStatement();
            // En choisissant nom_pays comme élément de recherche
            //ResultSet lrs = lstSQL.executeQuery("SELECT nom_pays FROM pays ORDER BY 1");
            
            //En choisissant l'id_pays comme élément de recherche
            ResultSet lrs = lstSQL.executeQuery("SELECT id_pays, nom_pays FROM pays ORDER BY 2");
            
            mapPays = new HashMap();

            idcbm = new DefaultComboBoxModel();
            while (lrs.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                idcbm.addElement(lrs.getString("nom_pays"));
                mapPays.put(lrs.getString("nom_pays"), lrs.getString("id_pays"));
            }
            jComboBoxPays.setModel(idcbm);

            lrs.close();
            lstSQL.close();

            jLabelMessage.setText("Veuillez choisir un pays à supprimer.");

        } catch (ClassNotFoundException | SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPaysASupprimer = new javax.swing.JLabel();
        jComboBoxPays = new javax.swing.JComboBox<>();
        jButtonValider = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Suppression Pays");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelPaysASupprimer.setText("Pays à supprimer ?");

        jComboBoxPays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPaysASupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaysASupprimer)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButtonValider)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        try {

            // DELETE
            //Recherche avec le nom du pays
            //String lsSQL = "DELETE FROM pays WHERE nom_pays=?";
            
            String lsSQL = "DELETE FROM pays WHERE id_pays = ?";

            PreparedStatement lpst = icn.prepareStatement(lsSQL);

            //Recherche avec le nom du pays
            //lpst.setString(1, jComboBoxPays.getSelectedItem().toString());
            
            //Méthode avec la recherche ID
            String lsNom = jComboBoxPays.getSelectedItem().toString();
            String lsId = mapPays.get(lsNom);
            System.out.println(lsNom);
            System.out.println(lsId);

            lpst.setString(1, lsId);

            lpst.executeUpdate();

            lpst.close();

            jLabelMessage.setText("Pays supprimé !!!");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        try {
            icn.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxPays;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPaysASupprimer;
    // End of variables declaration//GEN-END:variables
}
