/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rayanakel
 */
public class JIFVilles extends javax.swing.JInternalFrame {

    private Connection icn;

    /**
     * Creates new form JIFVilles
     */
    public JIFVilles() {
        initComponents();

        jTextFieldId.setText("ID");
        jTextFieldCp.setText("");
        jTextFieldNom.setText("");

        setTitle("CRUD Villes");
        setVisible(true);

        try {
            // --- Connexion
            String lsDSN = "jdbc:mysql://172.26.55.55:3306/cinescope2014";
            icn = DriverManager.getConnection(lsDSN, "p", "b");

            //Affichage des donnees de la table departement
            PreparedStatement lpst = icn.prepareStatement("SELECT * FROM ville");
            ResultSet lrs = lpst.executeQuery();

            Object[] tLigne;

            DefaultTableModel ldtm = (DefaultTableModel) jTableVilles.getModel();

            while (lrs.next()) {
                tLigne = new Object[3];

                tLigne[0] = lrs.getString(1);
                tLigne[1] = lrs.getString(2);
                tLigne[2] = lrs.getString(3);

                ldtm.addRow(tLigne);
            }

            lrs.close();
            lpst.close();

            jLabelMessage.setText("Chargement réussi !!");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVilles = new javax.swing.JTable();
        jLabelId = new javax.swing.JLabel();
        jLabelCp = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelDepartement = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jComboBoxDepartement = new javax.swing.JComboBox<>();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableVilles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableVilles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CP", "Nom", "Département"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVilles.setGridColor(new java.awt.Color(0, 0, 0));
        jTableVilles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVillesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVilles);

        jLabelId.setText("ID");

        jLabelCp.setText("CP");

        jLabelNom.setText("Nom");

        jLabelDepartement.setText("Département");

        jTextFieldId.setBackground(new java.awt.Color(238, 238, 238));
        jTextFieldId.setForeground(new java.awt.Color(255, 0, 0));
        jTextFieldId.setText("ID");
        jTextFieldId.setBorder(null);

        jComboBoxDepartement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDepartement.setActionCommand("");
        jComboBoxDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartementActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");

        jButtonSupprimer.setText("Supprimer");

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDepartement)
                                .addGap(44, 44, 44)
                                .addComponent(jComboBoxDepartement, 0, 127, Short.MAX_VALUE))
                            .addComponent(jLabelMessage)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNom)
                                    .addComponent(jLabelCp)
                                    .addComponent(jLabelId))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNom))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAjouter)
                        .addGap(147, 147, 147)
                        .addComponent(jButtonModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSupprimer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCp)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartement)
                    .addComponent(jComboBoxDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDepartementActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        if (jTextFieldCp.getText().isEmpty() || jTextFieldNom.getText().isEmpty() || jComboBoxDepartement.getSelectedIndex() == -1) {

            jLabelMessage.setText("Veuillez renseigner tout les champs!!");
        } else {
            try {

                // INSERTION
                String lsSQL = "INSERT INTO ville (cp, nom_ville) VALUES(?,?)";

                PreparedStatement lpst = icn.prepareStatement(lsSQL);

                //Recuperation des donnes dans les champs
                lpst.setString(1, jTextFieldCp.getText());
                lpst.setString(2, jTextFieldNom.getText());

                //Execution
                lpst.executeUpdate();

                Object[] tLigne;

                DefaultTableModel ldtm = (DefaultTableModel) jTableVilles.getModel();

                tLigne = new Object[3];

                tLigne[1] = jTextFieldCp.getText();
                tLigne[2] = jTextFieldNom.getText();

                ldtm.addRow(tLigne);

                lpst.close();

                jLabelMessage.setText("Ajout réussi !");

            } catch (SQLException ex) {
                jLabelMessage.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        try {
            icn.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTableVillesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVillesMouseClicked
        // TODO add your handling code here:
        int liSelectedRow = this.jTableVilles.getSelectedRow();

        jTextFieldId.setText(jTableVilles.getValueAt(liSelectedRow, 0).toString());
        jTextFieldCp.setText(jTableVilles.getValueAt(liSelectedRow, 1).toString());
        jTextFieldNom.setText(jTableVilles.getValueAt(liSelectedRow, 2).toString());
        jComboBoxDepartement.setSelectedItem(jTableVilles.getValueAt(liSelectedRow, 3).toString());
    }//GEN-LAST:event_jTableVillesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jComboBoxDepartement;
    private javax.swing.JLabel jLabelCp;
    private javax.swing.JLabel jLabelDepartement;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVilles;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
